source 'https://rubygems.org'

gem 'hetzner-docker', github: 'imelnik/hetzner-docker'
# gem 'hetzner-docker', path: './'
gem 'hetzner-api'
gem 'net-ssh'
gem 'net-scp'
gem 'knife-solo'
gem 'berkshelf', '~> 3.1.1'
gem 'slop'
